### ISSUE TITLE
octant 0.16.1 build issue

### ISSUE THREAD

**Issue by chenrui333** [vmware-tanzu/octant#1585]
👋  when homebrew-core regression testing the build, we found the `octant 0.16.1` has some build issue. Error log is below:

```
==> go run build.go web-build
npm notice
npm notice New patch version of npm available! 7.0.8 -> 7.0.9
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v7.0.9>
npm notice Run `npm install -g npm@7.0.9` to update!
npm notice
npm ERR! code ENOTFOUND
npm ERR! syscall getaddrinfo
npm ERR! errno ENOTFOUND
npm ERR! network request to http://build-artifactory.eng.vmware.com/api/npm/npm/latest-version/-/latest-version-5.1.0.tgz failed, reason: getaddrinfo ENOTFOUND build-artifactory.eng.vmware.com
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     /private/tmp/octant-20201108-91536-1fo9mzi/.brew_home/.npm/_logs/2020-11-08T15_46_11_416Z-debug.log
```

relates to https://github.com/Homebrew/homebrew-core/pull/64216

**Comment by wwitzel3** [comment]
Thank you for reporting this, this is fixed in master. We'll keep this issue open until we get the update published in homebrew.

**Comment by chenrui333** [comment]
@wwitzel3 it looks like I have run into this issue again in the most recent release, https://github.com/Homebrew/homebrew-core/pull/64622

**Comment by chenrui333** [comment]
Is there anyway that we can have some public access for the vmware artifactory url?
http://build-artifactory.eng.vmware.com/api/npm/npm/latest-version/-/latest-version-5.1.0.tgz failed, reason: getaddrinfo ENOTFOUND build-artifactory.eng.vmware.com

**Comment by wwitzel3** [comment]
This is now fixed in 0.16.2 which was released today.

**Comment by chenrui333** [comment]
Did a [new release bump](https://github.com/Homebrew/homebrew-core/pull/65406), still not working in my favor.
